# Generated by Django 5.1.2 on 2024-11-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='factor',
            field=models.FloatField(default=1.0),
        ),
    ]
